import { Cog, Layers, Lightbulb, Package } from 'lucide-react';
import type { Project } from './types';

export const allProjects: Project[] = [
  {
    title: 'Paket7',
    status: 'Live Production',
    statusColor: 'emerald',
    icon: Package,
    shortDesc: 'Package tracking aggregator for Turkish carriers.',
    myRole: 'Full-stack developer and product owner.',
    solution: 'Built a web application that aggregates tracking data from multiple Turkish carriers with real-time updates.',
    impact: 'Shipped and deployed a production web application serving real users.',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Vercel'],
    links: { live: 'https://paket7.com', repo: 'https://github.com/aybarutcu/paketbul' },
  },
  {
    title: 'TA Store Marketplace',
    status: 'Development',
    statusColor: 'purple',
    icon: Lightbulb,
    shortDesc: 'Headless commerce marketplace with a Medusa backend.',
    myRole: 'Full-stack developer using the Medusa commerce framework.',
    solution: 'Built a marketplace storefront with backend integration and payment processing.',
    impact: 'Learned about commerce platform architecture and design.',
    tech: ['Medusa', 'Next.js', 'React', 'Node.js', 'PostgreSQL', 'Stripe'],
    links: { repo: 'https://github.com/aybarutcu/ta-store' },
  },
  {
    title: 'Legal CRM — Sprint 0 Architecture',
    status: 'Architecture / Foundation Phase',
    statusColor: 'blue',
    icon: Layers,
    shortDesc: 'Legal practice management platform foundation.',
    myRole: 'System architect and foundation developer.',
    solution: 'Designed a CRM foundation with Next.js, Prisma, PostgreSQL, OpenAPI, Docker, CI/CD, and observability planning.',
    impact: 'Established a strong engineering foundation with ADRs, schema planning, and API definitions.',
    tech: ['Next.js 15', 'TypeScript', 'Prisma', 'PostgreSQL', 'OpenAPI', 'Docker'],
    links: { repo: 'https://github.com/aybarutcu/legal-crm-sprint0' },
  },
  {
    title: 'Automated User Lifecycle Management',
    status: 'Concept',
    statusColor: 'amber',
    icon: Cog,
    shortDesc: 'Automation for user provisioning workflows.',
    myRole: 'Designed the automation concept and workflow architecture.',
    solution: 'Explored AD and Microsoft 365 automation patterns with approval workflows and audit logging.',
    impact: 'Targeted a reduction in provisioning time from 30 minutes to 3 minutes per user.',
    tech: ['PowerShell', 'Python', 'Microsoft Graph', 'Active Directory'],
  },
  {
    title: 'Self-Service Support Automation',
    status: 'Prototype',
    statusColor: 'cyan',
    icon: Lightbulb,
    shortDesc: 'Self-service portal for repetitive IT support requests.',
    myRole: 'Prototyped the self-service platform architecture and user flows.',
    solution: 'Built a proof-of-concept portal for automated password resets and access requests.',
    impact: 'Prototyped a self-service portal for common support tasks.',
    tech: ['Node.js', 'Express', 'PowerShell', 'ServiceNow'],
  },
  {
    title: 'Internal Tools Containerization',
    status: 'Exploration',
    statusColor: 'violet',
    icon: Layers,
    shortDesc: 'Containerization strategy for internal utilities.',
    myRole: 'Researched deployment patterns and containerization strategy.',
    solution: 'Evaluated Docker-based packaging and lightweight CI/CD flows for internal tools.',
    impact: 'Explored containerization for internal tools.',
    tech: ['Docker', 'Git', 'CI'],
  },
];

export const featuredProjects = allProjects.slice(0, 3);
